print ('Введите координаты точки А')
print ('х=')
X=int(input())
print ('y=')
Y=int(input())
print ('Введите координаты точки B')
print ('х=')
A=int(input())
print ('y=')
B=int(input())
S=round((((A-X)**2+(B-Y)**2)**0.5),5)
print ('Расстояние между 2 точками=')
print (S)